//this file is autogenerated on the date 2019-08-13 21:18:12
using UnityEngine;
using UnityEditor;

public static class ScenesToMenuItems
{
	[MenuItem("Scenes/Arena")]
	private static void SCENE_ARENA ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/Arena.unity");
	}

	[MenuItem("Scenes/CombatTest")]
	private static void SCENE_COMBATTEST ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/CombatTest.unity");
	}

	[MenuItem("Scenes/Hub")]
	private static void SCENE_HUB ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/Hub.unity");
	}

	[MenuItem("Scenes/ItemTest")]
	private static void SCENE_ITEMTEST ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/ItemTest.unity");
	}

	[MenuItem("Scenes/MainMenu")]
	private static void SCENE_MAINMENU ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/MainMenu.unity");
	}

}
