//this file is autogenerated on the date 2019-08-01 15:02:52
using UnityEngine;
using UnityEditor;

public static class ScenesToMenuItems
{
	[MenuItem("Scenes/MainMenu")]
	private static void SCENE_MAINMENU ()
	{
		UnityEditor.SceneManagement.EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo ();
		UnityEditor.SceneManagement.EditorSceneManager.OpenScene ("Assets/Scenes/MainMenu.unity");
	}

}
